# Generated by Django 3.2.5 on 2021-07-09 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_dingtalk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dingtalk', 'dingtalk')], max_length=128, verbose_name='报警后端类型')),
                ('status', models.IntegerField(choices=[(0, '开启'), (1, '关闭')], default=0, verbose_name='状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('config', models.JSONField(default=user.models.default_json, verbose_name='报警配置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户报警信息',
                'verbose_name_plural': '用户报警信息',
            },
        ),
    ]
