# Generated by Django 3.2.5 on 2021-07-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_auto_20210709_0037'),
        ('user', '0003_useralertconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_alert_server',
            field=models.ManyToManyField(to='alert.GroupAlertServer', verbose_name='报警服务组'),
        ),
        migrations.AlterField(
            model_name='useralertconfig',
            name='type',
            field=models.CharField(choices=[('sms_ali', 'sms_ali'), ('dingtalk', 'dingtalk'), ('email', 'email')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
