# Generated by Django 3.2.5 on 2021-07-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210709_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertconfig',
            name='type',
            field=models.CharField(choices=[('sms_ali', 'sms_ali'), ('email', 'email'), ('dingtalk', 'dingtalk')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
