# Generated by Django 3.2.5 on 2021-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210713_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertconfig',
            name='type',
            field=models.CharField(choices=[('wx_group', 'wx_group'), ('email', 'email'), ('dingtalk', 'dingtalk'), ('wx_application', 'wx_application'), ('sms_ali', 'sms_ali')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
