# Generated by Django 3.2.5 on 2021-07-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_useralertconfig_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '开启'), (1, '关闭')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='useralertconfig',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('dingtalk', 'dingtalk'), ('wx_group', 'wx_group'), ('wx_application', 'wx_application'), ('sms_ali', 'sms_ali')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
