# Generated by Django 3.2.5 on 2021-07-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210723_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAlertConfig',
        ),
    ]
