# Generated by Django 3.2.5 on 2021-07-07 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertbankend',
            options={'verbose_name': '报警后端', 'verbose_name_plural': '报警后端'},
        ),
        migrations.AddField(
            model_name='alertbankend',
            name='bankend',
            field=models.CharField(choices=[], default=1, max_length=128, verbose_name='报警后端类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertbankend',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertbankend',
            name='status',
            field=models.IntegerField(choices=[(0, '开启'), (1, '关闭')], default=0, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='alertbankend',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='alertbankend',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
