# Generated by Django 3.2.5 on 2021-07-10 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0003_auto_20210709_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupalertserver',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='创建用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupalertserver',
            name='type',
            field=models.CharField(choices=[('sms_ali', 'sms_ali'), ('email', 'email'), ('dingtalk', 'dingtalk')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
