# Generated by Django 3.2.5 on 2021-07-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_auto_20210710_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupalertserver',
            name='type',
            field=models.CharField(choices=[('sms_ali', 'sms_ali'), ('dingtalk', 'dingtalk'), ('wx_group', 'wx_group'), ('wx_application', 'wx_application'), ('email', 'email')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
