# Generated by Django 3.2.5 on 2021-07-15 23:43

import alert.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alert', '0005_alter_groupalertserver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupalertserver',
            name='type',
            field=models.CharField(choices=[('wx_group', 'wx_group'), ('email', 'email'), ('dingtalk', 'dingtalk'), ('wx_application', 'wx_application'), ('sms_ali', 'sms_ali')], max_length=128, verbose_name='报警后端类型'),
        ),
        migrations.CreateModel(
            name='SendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('request_data', models.JSONField(default=alert.models.default_json, verbose_name='请求内容')),
                ('respones_data', models.JSONField(default=alert.models.default_json, verbose_name='请求内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送用户')),
            ],
            options={
                'verbose_name': '发送历史内容',
                'verbose_name_plural': '发送历史内容',
            },
        ),
    ]
