# Generated by Django 3.2.5 on 2021-07-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_auto_20210721_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupalertserver',
            name='type',
            field=models.CharField(choices=[('email', 'email'), ('dingtalk', 'dingtalk'), ('wx_group', 'wx_group'), ('wx_application', 'wx_application'), ('sms_ali', 'sms_ali')], max_length=128, verbose_name='报警后端类型'),
        ),
    ]
